"""empty message

Revision ID: 374225b4e19b
Revises: ed61d845d082
Create Date: 2022-06-02 16:28:21.448643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374225b4e19b'
down_revision = 'ed61d845d082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_table('Genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('genres',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Genre.id'], name='genres_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='genres_pkey')
    )
    # ### end Alembic commands ###
