"""empty message

Revision ID: ac2d9ec53ba8
Revises: acd518f05dd0
Create Date: 2022-06-02 16:41:09.236862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2d9ec53ba8'
down_revision = 'acd518f05dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Genre_venue_id'), 'Genre', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'Genre', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_index(op.f('ix_Genre_venue_id'), table_name='Genre')
    op.drop_column('Genre', 'venue_id')
    # ### end Alembic commands ###
