"""empty message

Revision ID: acd518f05dd0
Revises: 49a501c91560
Create Date: 2022-06-02 16:33:38.707199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd518f05dd0'
down_revision = '49a501c91560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Venue.id'], )
    )
    op.drop_table('Tag')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Venue.id'], name='tags_id_fkey')
    )
    op.create_table('Tag',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tag_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Tag_pkey')
    )
    op.drop_table('genres')
    op.drop_table('Genre')
    # ### end Alembic commands ###
